#!/usr/bin/env python3
"""Interface-thickness study on the TC1/Fig 5 conduction sweep: smooth_coeff 0.5 vs 0.99.

Fig 5 (case1_fig5.png) overlays the w064 conduction sweep (Ma = 0.1, 0.01, 0.001). The
default interface is smooth_coeff = 0.5 (half-width w = dx/smooth_coeff = 2*dx); this study
adds the sharper smooth_coeff = 0.99 (w ~ dx, ~2x sharper) so the effect of interface
thickness on the rise velocity can be read off.

IMPORTANT: the 0.5 baselines already on disk were generated by an OLDER case (10*t_r window).
The committed case now uses a 2*t_r window, so this driver REGENERATES BOTH interfaces from
the current committed case -- the only difference between a pair is smooth_coeff. Each variant
copies case_Ma_0.py into runs/<name>/ and rewrites the `Ma =`, `Nx =`, and smooth_coeff
lines; the committed case file is never touched (mirrors run.py).

Run dirs:  tc1/<ma>/w064/sc<050|099>
Usage:     python3 run_sc099.py [ranks]     (runs every missing combo in parallel)
"""

import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
RUNS = os.path.join(HERE, "runs")
CASE = "case_Ma_0.py"
NX = 64

PIN = ["taskset", "-c", "180-255"]  # off cores 0-165, where the concurrent ygb sweep is pinned
NOBIND = {"OMPI_MCA_hwloc_base_binding_policy": "none"}

MAS = {"ma0p1": "0.1", "ma0p01": "0.01", "ma0p001": "0.001"}
SCS = {"sc050": "0.5", "sc099": "0.99"}


def expected_stop(wd):
    inp = os.path.join(wd, "simulation.inp")
    if not os.path.isfile(inp):
        return None
    for line in open(inp):
        if line.strip().startswith("t_step_stop"):
            return int(line.split("=", 1)[1])
    return None


def is_done(wd):
    """True if the run reached its t_step_stop (final checkpoint present)."""
    stop = expected_stop(wd)
    if stop is None:
        return False
    return os.path.isfile(os.path.join(wd, "restart_data", f"lustre_{stop}.dat"))


def prepare(ma_lbl, sc_lbl):
    name = f"tc1/{ma_lbl}/w064/{sc_lbl}"
    wd = os.path.join(RUNS, name)
    if os.path.isdir(wd):
        shutil.rmtree(wd)
    os.makedirs(wd)
    dst = os.path.join(wd, CASE)
    text = open(os.path.join(HERE, CASE)).read()
    text, a = re.subn(r"(?m)^Ma = [0-9.]+", f"Ma = {MAS[ma_lbl]}", text, count=1)
    text, b = re.subn(r"(?m)^Nx = \d+", f"Nx = {NX}", text, count=1)
    text, c = re.subn(r'"patch_icpp\(2\)%smooth_coeff": [0-9.]+', f'"patch_icpp(2)%smooth_coeff": {SCS[sc_lbl]}', text, count=1)
    assert a == 1 and b == 1 and c == 1, f"{name}: rewrite miss Ma={a} Nx={b} sc={c}"
    open(dst, "w").write(text)
    return name, wd, os.path.relpath(dst, REPO)


def main():
    ranks = int(sys.argv[1]) if len(sys.argv) > 1 else 6
    jobs = []
    for ma_lbl in MAS:
        for sc_lbl in SCS:
            name = f"tc1/{ma_lbl}/w064/{sc_lbl}"
            if is_done(os.path.join(RUNS, name)):
                print(f"skip {name}: already complete", flush=True)
                continue
            n, wd, rel = prepare(ma_lbl, sc_lbl)
            log = open(os.path.join(wd, "run.log"), "w")
            p = subprocess.Popen(
                PIN + ["./mfc.sh", "run", rel, "-n", str(ranks)],
                cwd=REPO,
                env={**os.environ, **NOBIND},
                stdout=log,
                stderr=subprocess.STDOUT,
            )
            jobs.append((n, p, log))
            print(f"launched {n} (pid {p.pid})", flush=True)

    rc = 0
    for n, p, log in jobs:
        p.wait()
        log.close()
        print(f"done {n}: exit {p.returncode}", flush=True)
        rc |= p.returncode
    sys.exit(rc)


if __name__ == "__main__":
    main()
